### ISSUE TITLE
Insufficient client scope

### ISSUE THREAD

**Issue by stnokott** [SLG/home-assistant-addons#1]
Successfully authenticated, but getting this error when running the REST command (running as HA Addon):

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
> spotify-sync@0.0.1 start
> ts-node src/index.ts
Listening on 8833
Logged in!
Now 2022-08-07T19:04:29.030Z
Last synced 1970-01-01T00:00:00.000Z
Remove recently played songs
Failed to do my job WebapiRegularError: An error occurred while communicating with Spotify's Web API.
Details: Insufficient client scope.
    at _toError (/node_modules/spotify-web-api-node/src/http-manager.js:39:12)
    at fn (/node_modules/spotify-web-api-node/src/http-manager.js:71:25)
    at Request.callback (/node_modules/superagent/src/node/index.js:902:3)
    at fn (/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.<anonymous> (/node_modules/superagent/src/node/parsers/json.js:19:7)
    at Stream.emit (node:events:527:28)
    at Stream.emit (node:domain:475:12)
    at Unzip.<anonymous> (/node_modules/superagent/src/node/unzip.js:54:12)
    at Unzip.emit (node:events:527:28)
    at Unzip.emit (node:domain:475:12) {
  body: { error: { status: 403, message: 'Insufficient client scope' } },
  headers: {
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'private, max-age=0',
    'x-robots-tag': 'noindex, nofollow',
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'Accept, App-Platform, Authorization, Content-Type, Origin, Retry-After, Spotify-App-Version, X-Cloud-Trace-Context, client-token, content-access-token',
    'access-control-allow-methods': 'GET, POST, OPTIONS, PUT, DELETE, PATCH',
    'access-control-allow-credentials': 'true',
    'access-control-max-age': '604800',
    'content-encoding': 'gzip',
    'strict-transport-security': 'max-age=31536000',
    'x-content-type-options': 'nosniff',
    date: 'Sun, 07 Aug 2022 19:04:28 GMT',
    server: 'envoy',
    via: 'HTTP/2 edgeproxy, 1.1 google',
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
    connection: 'close',
    'transfer-encoding': 'chunked'
  },
  statusCode: 403
}
```

Any idea what the issue might be?

**Comment by stnokott** [comment]
I might have found the issue:

The OAuth URL generated by `getCode` only has the `playlist-modify-private` scope, but not the `playlist-modify-public` scope:
https://github.com/SLG/home-assistant-addons/blob/fb0f9297321d41f7950713c3ea1914bbb8a9b6a0/spotify-sync/src/index.ts#L47-L49

This means, when the playlist the addon should modify is public, the scope does not suffice.
Once I set my playlist from public to private, everything worked fine.

I'd suggest simply adding the `playlist-modify-public` scope. (I'd open up a MR, but that's too small of an issue for a whole fork)

**Comment by SLG** [comment]
Ah, makes sense. My own playlist is private. I've added the other scope. Let me know if it worked.

**Comment by stnokott** [comment]
Yes, fixed. Thanks!
